// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"go-tutorial/project/wire_learn/wire_pkg_demo"
)

// Injectors from wire.go:

func InitializeC(ctx context.Context, name string, age int) (wire_pkg_demo.C, error) {
	a := wire_pkg_demo.NewA(name, age)
	b := wire_pkg_demo.NewB(a)
	c, err := wire_pkg_demo.NewC(ctx, b)
	if err != nil {
		return wire_pkg_demo.C{}, err
	}
	return c, nil
}
