// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User 用户表
type User struct {
	UserID    int64  `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:用户ID" json:"user_id"` // 用户ID
	Name      string `gorm:"column:name;not null;comment:姓名" json:"name"`                              // 姓名
	Gender    int32  `gorm:"column:gender;not null;default:2;comment:性别，1=男，0=女，2=保密" json:"gender"`   // 性别，1=男，0=女，2=保密
	Version   int32  `gorm:"column:version;not null;default:1;comment:版本号" json:"version"`             // 版本号
	CreatedAt int32  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                // 创建时间
	UpdatedAt int32  `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
